hughsie/libgusb

gusb/Makefile.am, gusb/libgusb.ver
I started the map based on the 'auto export filter' (g_usb_*, marking those as 'LIBGUSB_0.1.0' and the rest * as local.
Then I parsed the .c files finding all functions that had a 'Since: ' tag, adding them to the respective version block (with correct inheritance)
Seeing that libgusb is rather new, this is still a doable effort. It would avoid cases as were discussed today where a user updates one package, but not the lib to it: with versioned symbols, RPM would have told this lib is needed (and higher level PMs, like PackageKit, would have triggered the lib for an  update).
=> use symbol versioning

gusb/gusb-context.c, gusb/gusb-device-list.c, gusb/gusb-device.c
This allows g_usb_context_get_devices, usb_device_list_get_devices and
g_usb_device_get_children to be used in languages that use gobject
introspection like Vala, Python etc.
=> Add missing element-type annotations.

gusb/Makefile.am, gusb/gusb-autocleanups.h
This allows using e.g. g_autoptr(GUsbDevice) in other programs, but does
not make libgusb itself use g_autoptr, or require a new enough glib to
support it.
=> Support g_autoptr() for all gusb object types

gusb/libgusb.ver
:( a couple of symbols have wrongly been exported as benig part of libusb_0.1.0
It's quite important to add new symbols accordingly when they appear.
=> Fixup symbol version table up to version 0.2.9

docs/api/Makefile.am
This fixes the following error;
```
warning: failed to load external entity "../xml/gusb-context.xml"
../gusb-docs.sgml:49: element include: XInclude error : could not load ../xml/gusb-context.xml, and no fallback was found
warning: failed to load external entity "../xml/gusb-source.xml"
../gusb-docs.sgml:50: element include: XInclude error : could not load ../xml/gusb-source.xml, and no fallback was found
warning: failed to load external entity "../xml/gusb-device.xml"
../gusb-docs.sgml:51: element include: XInclude error : could not load ../xml/gusb-device.xml, and no fallback was found
warning: failed to load external entity "../xml/gusb-device-list.xml"
../gusb-docs.sgml:52: element include: XInclude error : could not load ../xml/gusb-device-list.xml, and no fallback was found …
```
=> Fix gtk-doc build when builddir != srcdir

gusb/meson.build
This fixes cross building of gir using Yocto Project/Buildroot
method.
This is also done on atk with -DATK_COMPILATION and
gdk-pixbuf with -DGDK_PIXBUF_COMPILATION.
=> gusb/meson.build: pass -DGUSB_COMPILATION to gir compiler

meson.build
This means we still get errors for missing enum values in switches even
in combination with -Wswitch-default and default cases.
=> build: Add -Wswitch-enum

gusb/gusb-device.c
the actual_length parameter of GUsbDevice's transfer-methods should
be out parameters. otherwise the generated vala bindings will cause
programs to segfault.
=> gi: made actual_length introspection annotations

gusb/gusb-context.c
In 985b9e4ec39ac521e7398a8e3017c96f2c4d75ec I mistakenly thought this was the
timeout for the added/removed context checking, which was Windows-specific.
It actually was the main context event thread, which is running all the time.
Switch the poll timeout to be 2s, (still down from the default 60s!) which is a
better compromise between battery life and context shutdown performance.
Fixes https://github.com/hughsie/libgusb/issues/24
=> Fix high number of wakeups when checking the GUsbContext

gusb/gusb-device.c
The existing logic here was unsound; the recursion only checked the string for
length 0 after it had gone up the tree to the parent, and so would never match.
This meant if you had identical devices with the same port hierarchy on
different USB busses they had the *same* physical ID. This really upsets
projects like fwupd which use the physical ID to stay the same on device replug
(which worked fine), but also dedupe devices with the same physical ID, which
is what broke here.
=> Include the USB bus in the generated platform_id

contrib/ci/Dockerfile-fedora, contrib/generate-version-script.py, gusb/libgusb.ver
This resulted in losing g_usb_source_set_callback@LIBGUSB_0.1.0 from
the ABI in version 0.3.4.
---
Includes #32, please review that first.
I'm trying to work out a way to address #9 and #27 by generating *both* versions - the old, wrong one and the new, correct one - so that a future GUsb will have an ABI that is a superset of every historical version. I haven't got that working yet, but I discovered this bug while trying to get there.
=> generate-version-script: Don't skip methods on plain structs

contrib/generate-version-script.py, gusb/meson.build
Python can be installed in different directories on different operating
systems, so we can't hard-code the path of it. Instead it, just use the
usual '#!/usr/bin/env' to find it with PATH.
=> generate-version-script: Don't hard-code the path of python3

docs/api/meson.build, gusb/meson.build
Fixes https://github.com/fwupd/fwupd/issues/2178
=> Allow building GtkDoc when building as a subproject

gusb/gusb-device.c, gusb/gusb-device.h, gusb/libgusb.ver
Adds a getter for a gusb_device to get the string index for the active
configuration's description.
=> Add a way to get iConfiguration

gusb/meson.build, meson.build
This is a replacement/alternative to #38. The build in that PR is failing because Homebrew currently builds `libgusb` using an older, patched version of `meson` that does some magic with macOS dylib versioning. We've had to use this because it turns out that as many projects transitioned from `autotools` to `meson`, dylib versioning broke - the switch would often result in a perceived downgrade of the dylib version when this was not the case.
This PR fixes the dylib versioning issue, which will allow us at Homebrew to build with a non-patched, current `meson`, which will eliminate the need for the changes proposed in #38. For context, some other projects (notably GNOME) have implemented similar fixes:
- https://gitlab.gnome.org/GNOME/gtk/commit/e65699e9c167b08b8ce3cea5d3abbdf525137eac
- …
=> Properly set dylib versions on darwin

gusb/gusb-device.c
libusb can only handle cancellation if the transfer is already
in-flight. However, g_cancellable_connect will immediately call the
callback and then libusb_cancel_transfer when the cancellable is already
cancelled at the time the transfer is submitted.
Move the cancellation registration to after transfer submission to avoid
ordering issues. Also avoid even submitting the transfer if the
cancellable is already cancelled to begin with.
=> device: Fix cancellation if cancellable is already cancelled

gusb/gusb-device.c, gusb/gusb-device.h, gusb/libgusb.ver
This is requried for the GD32VF103 device.
=> Add g_usb_device_get_string_descriptor_bytes()

gusb/gusb-device.c
Currently gusb-device adds two references to an internal libusb device,
causing a memory leak on destruction.
In fact, we add a reference when the device is constructed and when the
device is inited.
To avoid this and ensure that libusb will cleanup all the devices on
context destruction, only reference on device initialization.
---
As context, in [libfprint we had this leak](https://gitlab.freedesktop.org/3v1n0/libfprint/-/jobs/8831654/artifacts/file/_build/meson-logs/testlog-valgrind.txt) for some long time, and I initially thought was due to libusb... But it's not the case, in fact using libusb in debug mode will warn about the application not releasing a device.
```
==326037== 
==326037== HEAP SUMMARY:
==326037==     in use at exit: 1,206,244 bytes in 3,664 blocks
==326037==   total …
```
=> device: Do not double-reference USB devices

gusb/gusb-device.c, gusb/gusb-device.h, gusb/libgusb.ver
Some devices won't answer to a request with a 128-byte data buffer, this
allows the user to specify the size of the request data
buffer. g_usb_device_get_string_descriptor_bytes still uses the default
buffer size (128 bytes).
=> Add g_usb_device_get_string_descriptor_bytes_full

.github/workflows/main.yml, gusb/gusb-context.c
Somehow this worked when we unref'd the context but did not ref it.
=> Fix hotplug after threaded device removal

gusb/gusb-device.c, gusb/gusb-device.h, gusb/libgusb.ver
This can speed up device enumeration, and also allows us to emulate the
interfaces or descriptors in the future.
=> Cache the list of interfaces and descriptors

gusb/gusb-device-event-private.h, gusb/gusb-device-event.c, gusb/gusb-device-event.h, gusb/gusb-device.c, gusb/libgusb.ver
This is required to emulate devices that just reset (without completing the current transfer) when asked to reset.
=> Allow emulating failed events

gusb/gusb-device-private.h, gusb/gusb-device.c, gusb/gusb-device.h, gusb/libgusb.ver
This allows us to see which phase of the emulation should be used.
=> Allow adding tags to the JSON device event

gusb/gusb-context.c
If we call libusb_get_bos_descriptor() in the hotplug device-add handler then we eventually call libusb_handle_events_completed() which can run handle_events -- which might emit devices.
Using a mutex that's safe for recursing prevents the deadlock.
This fixes half the problem when getting descriptors on deeply nested USB hubs.
=> Use GRecMutex to avoid a single-threaded lockup

gusb/gusb-interface.c
When the g_usb_interface is created from _g_usb_device_load(), self->endpoints may not be initialized.
Load GUsb endpoints when loading interface.
=> Fix g_usb_interface save and load

gusb/gusb-context.c, gusb/gusb-device-event-private.h, gusb/gusb-device-event.c, gusb/gusb-device-event.h, gusb/gusb-device.c, gusb/libgusb.ver
If the return code is LIBUSB_ERROR_NO_DEVICE we want to record that.
=> Save the libusb error if libusb_submit_transfer() fails

gusb/gusb-bos-descriptor.c, gusb/gusb-device-event.c, gusb/gusb-device.c, gusb/gusb-endpoint.c, gusb/gusb-interface.c, gusb/gusb-json-common.c, gusb/gusb-json-common.h, gusb/meson.build
json library previous to version 1.6.0 doesn't provide the `json_object_get_*_member_with_default()` functions.
=> Add json_object_get_*_member_with_default() helpers

gusb/gusb-device.c
The reply to an out-of-order outgoing BulkTransfer may be also out-of-order.
Currently we can get:
```
found in-order BulkTransfer:Endpoint=0x01,Data=…,Length=0x25 at position 315
found in-order BulkTransfer:Endpoint=0x82,Data=…,Length=0x25 at position 316
…
found out-of-order BulkTransfer:Endpoint=0x01,Data=…,Length=0x25 at position 312
found in-order BulkTransfer:Endpoint=0x82,Data=…,Length=0x25 at position 320
```
while expecting:
```
found in-order BulkTransfer:Endpoint=0x01,Data=…,Length=0x25 at position 315
found in-order BulkTransfer:Endpoint=0x82,Data=…,Length=0x25 at position 316
…
found out-of-order BulkTransfer:Endpoint=0x01,Data=…,Length=0x25 at position 312
found in-order BulkTransfer:Endpoint=0x82,Data=…,Length=0x25 at position 314
…
found in-order …
```
=> Fix BulkTransfer out-of-order reply

gusb/gusb-context.c, gusb/gusb-device.c
```
This fixes compiling with clang 16 in 32 bit mingw environment.
Here is the compiler error:
../gusb/gusb-device.c:2298:10: error: incompatible function pointer types passing
'void (struct libusb_transfer *)' to parameter of type 'libusb_transfer_cb_fn'
(aka 'void (*)(struct libusb_transfer *) __attribute__((stdcall))')
[-Wincompatible-function-pointer-types]
```
=> Add calling convention to libusb callback functions

.github/workflows/main.yml
Node.js 12 actions are deprecated. These actions are using Node.js 16.
=> trivial: Update GitHub Actions versions

gusb/gusb-device.c, gusb/gusb-device.h
In client code we have to handle it differently from _NO_DEVICE.
=> Add an device error code for 'busy'

gusb/gusb-device.c
Fixes https://github.com/hughsie/libgusb/issues/114
=> Allow reading HID descriptors larger than 255 bytes

gusb/gusb-device.c
See https://techcommunity.microsoft.com/t5/microsoft-usb-blog/usb-2-1-2-0-1-1-device-enumeration-changes-in-windows-8/ba-p/270775
=> Only request the BOS descriptor when bcdUSB > 0x0200
